### PR TITLE
Dict selection for peakfinding

### PR DESCRIPTION
**Pull request by ericpre**
More bug fixes and add tests for https://github.com/hyperspy/hyperspy/pull/2647.

### CODE REVIEW

**Comment by ericpre** [comment]
ping @pc494.

**Review by pc494 — APPROVED** [review]
Looks good to me, sorry for the delay in this review.

**Comment by ericpre** [comment]
Can you merge it then?

**Comment by pc494** [comment]
Sorry @ericpre I got very confused as I had assumed this was a PR to the upstream repo.

**Comment by ericpre** [comment]
Thanks, no worries!

**Pull request merged**
